### ISSUE TITLE
Use configured protocol for API requests

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#125]
@mdeuser commented on [Tue Oct 17 2017](https://github.com/apache/incubator-openwhisk/issues/2862)

See https://github.com/apache/incubator-openwhisk-cli/blob/master/commands/api.go#L916

Instead of hardcoding the protocol to `https` use the protocol configured in the apihost

---

@jsanda commented on [Fri Oct 27 2017](https://github.com/apache/incubator-openwhisk/issues/2862#issuecomment-340133925)

I submitted [PR 2909](https://github.com/apache/incubator-openwhisk/pull/2909) for this.

**Comment by dgrove-oss** [comment]
I just got bit by this today when trying to use `wsk api create` with a .wskprops that was "misconfigured" to have `APIHOST=https://MY_HOST` instead of `APIHOST=MY_HOST`.  The symptom was that invoking the resulting APIs gave a 502 (bad gateway) because the created actions were given the url `https://https://MY_HOST/`
