### ISSUE TITLE
Availability of CLI via Homebrew

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-cli#153]
@andrepoleza commented on [Mon Aug 15 2016](https://github.com/apache/incubator-openwhisk/issues/1064)

Hello!

I've read the documentation and became (more) interested in OpenWhisk, but I've notice that the CLI isn't published on Homebrew... Is there a reason to not be there?

---

@csantanapr commented on [Mon Aug 15 2016](https://github.com/apache/incubator-openwhisk/issues/1064#issuecomment-239986195)

Hi @andrepoleza for your interest in OpenWhisk.
We have no specific reason why the CLI is not available thru Homebrew.
I think homebrew is a good way of installing dev tools, and it could be a good vehicle to distribute the CLI.

Like anything it would take effort to get it done and also maintain it current (automation CI/CD).

We also need to do some bit of research on how to handle, nightly publish vs. a stable build with the current situation that the CLI doesn't have a semantic version only a hash or build id (i.e. date stamp)

I think after we figured out this we could also potentially offer the CLI thru other package manager (i.e. npm install -g whisk-cli)

I will keep the issue open to keep this a a enhancement request.

---

@andrepoleza commented on [Tue Aug 16 2016](https://github.com/apache/incubator-openwhisk/issues/1064#issuecomment-240182159)

Good to know! I've never thought about the semantic version and its impact on availability on Homebrew. I just think that distributing the CLI through a broader package manager would benefit OpenWhisk in several ways, because although npm and pip are stable/popular not every (potential) developer uses them.

Anyway, I'll be happy when OpenWhisk reaches Homebrew. 😃 

---

@jthomas commented on [Fri Oct 14 2016](https://github.com/apache/incubator-openwhisk/issues/1064#issuecomment-253771839)

I did an experiment with exposing the CLI through Homebrew recently.
https://github.com/jthomas/homebrew-tools/blob/master/wsk.rb

It worked perfectly although this file now fails the checksum test because the Go CLI has been updated. 

If we could work out how to trigger building this file when the Go CLI changes, you can just drop that repo in the OpenWhisk org and it'll work.

---

@dubeejw commented on [Tue Oct 18 2016](https://github.com/apache/incubator-openwhisk/issues/1064#issuecomment-254629085)

@jthomas, we could create the needed file during the CLI build, and add the required checksum during that process as well.

---

@jthomas commented on [Tue Oct 18 2016](https://github.com/apache/incubator-openwhisk/issues/1064#issuecomment-254642338)

That would be awesome.

**Comment by mgernand** [comment]
Any news on this one?

**Comment by csantanapr** [comment]
I think if generate checksum files and include as part of the release attachments we could integrate using homebrew tap

**Comment by Juice10** [comment]
I would love to see this one! A lot of our documentation infers you magically have `wsk` set in your shell's `$PATH`. It's super confusing for users new to the project. 

I personally actually went down the rabbit hole of compiling my own `wsk` cli because I wasn't sure what the appropriate steps where to install it.

Distributing the cli via brew, apt-get and the windows equivalent will help tremendously as we can just list our cli install step to be
> On Mac, install [homebrew](https://brew.sh) if you haven't already. Then run `$ brew install wsk`

and have the whole thing be basically fool proof.

**Comment by dubee** [comment]
@Juice10, after doing a deployment of OpenWhisk with Ansible the CLI should be available in the `bin` directory of cloned OpenWhisk repo.

@mdeuser, @drcariel, FYI on the above comment.

**Comment by drcariel** [comment]
related to my frustrations here - although outdated:
https://github.com/apache/incubator-openwhisk/issues/2449

**Comment by drcariel** [comment]
related to https://github.com/apache/incubator-openwhisk/issues/1880

**Comment by Juice10** [comment]
I submitted `wsk` & `wskdeploy` to Homebrew: https://github.com/Homebrew/homebrew-core/pull/31231

**Comment by shazron** [comment]
The latest `wsk` includes `wskdeploy`, we need to get this into homebrew
1. https://lists.apache.org/thread.html/6aa61b1ceb25a29e93bb524ca2afcac13440aca70632fb24a4ccc542@%3Cdev.openwhisk.apache.org%3E
2. https://github.com/Homebrew/homebrew-core/blob/e2771dbf5b0c80b6ac9b1ab46391a9c9fdfe9995/Formula/wsk.rb

**Comment by csantanapr** [comment]
We need a new Apache version voted and released like “0.10.0-incubating” first

**Comment by alexkli** [comment]
Both [wsk](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wsk.rb) and [wskdeploy](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wskdeploy.rb) are now available on homebrew. So I think this issue can be closed.

**However**, for `wsk` only the 6 month old 0.0.9-incubating version is available, while the [latest release](https://github.com/apache/incubator-openwhisk-cli/releases/tag/latest) isn't - and it includes some important new features like concurrency.

As a quick fix, I added a custom `wsk-latest` formula in my custom homebrew tap:

```
# only if you have wsk installed through homebrew
brew unlink wsk

brew tap alexkli/tap
brew install alexkli/tap/wsk-latest

wsk property get --cliversion
> whisk CLI version	2019-01-26T20:01:45.357+0000
```

But this is a bit annoying because of the `brew unlink` and switching back and forth between the two. With a separate formula, homebrew does not know that this is the same software, just a pre-release version.

IIUC, `latest` is not considered a stable release (e.g. it does not have a version number) and would be opt-in for early adopters. In Homebrew this can be done properly by adding a [devel version](https://docs.brew.sh/Formula-Cookbook#unstable-versions-devel-head) in the formula, that can be installed using `brew install --devel wsk`.

Would be cool if someone wants to tackle that - I could maybe in 2 weeks. And should that be a separate issue?

**Comment by csantanapr** [comment]
I was not aware of the —devel flag it would awesome if someone can implement this +1

**Comment by rabbah** [comment]
Created #410.
